version: "3.1"
services:
  api-transparencia:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "npm install && adonis serve --dev"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 3333:3333
    depends_on:
      - db-transparencia
  db-transparencia:
    build:
      context: .
      dockerfile: ./Dockerfile.db
    restart: always
    ports:
      - 5432:5432  
    environment:
      - POSTGRES_TEST_DATABASES=isac-tranparencia-api
      - POSTGRES_USER=isac-tranparencia-api
      - POSTGRES_PASSWORD=isac-tranparencia-api
      - PG_PASSWORD=isac-tranparencia-api